/* eslint-disable */
/* This file is autogenerated, see codegen.yml */


      export interface PossibleTypesResultData {
        possibleTypes: {
          [key: string]: string[]
        }
      }
      const result: PossibleTypesResultData = {
  "possibleTypes": {}
};
      export default result;
    
// Generated on 2022-01-30T21:06:11+00:00
